language: bash
sudo: required

services:
    - docker

script:
    # set up another Ubuntu 14.04 in Docker
    - docker pull ubuntu:14.04 
    - `docker run --name=box -d ubuntu:14.04`
    - docker ps -l
    - sudo ls /var/lib/docker/aufs/mnt/
    - tar -cv hello | docker exec -i box tar x -C /root
    - docker run box ls /root
